---
title: "Supplemental Information"
output: word_document
date: "2024-11-09"
---

```{r setup, include = FALSE}
library("papaja")
knitr::opts_chunk$set(include = FALSE)
```

```{r code setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE
)
library('tidyverse')
library("purrr")
library("uuid")
library('lubridate')
library('ggplot2')
library('lme4')
library('car')
library('report')
library('ggthemes')
library('emmeans')

library('cowplot')
library('prmisc')

library('chisq.posthoc.test')

library('performance')
library('AICcmodavg')

theme_set(theme_classic())

# The palette with black:
cbPalette <- c("#E69F00", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#56B4E9", "#CC79A7", "#000000")
```

```{r get data}
df.ppt_raw_1 <- read.csv('../../../data/exp1/PROCESSED_DATA/exp1_ppt.csv')
df.trial_raw_1 <- read.csv('../../../data/exp1/PROCESSED_DATA/exp1_trial.csv')

df.ppt_raw_2 <- read.csv('../../../data/exp2/PROCESSED_DATA/exp2_ppt.csv')
df.trial_raw_2 <- read.csv('../../../data/exp2/PROCESSED_DATA/exp2_trial.csv')
```

```{r study1 - exclusions}
#exclusions go here (or in a separate thing)
# exclude participants who missed more than 1 trial (completed fewer than 5)
ppt_excluded_completion_1 <- df.trial_raw_1 %>% 
  filter(is.na(count)) %>%
  group_by(id) %>%
  summarise(n_no_count = n()) %>%
  filter(n_no_count > 1) %>%
  pull(id)

df.ppt_1 <- df.ppt_raw_1 %>%
  filter(!id %in% ppt_excluded_completion_1)

df.trial_1 <- df.trial_raw_1 %>%
  filter(!id %in% ppt_excluded_completion_1, 
         exclude != "Y")
```

```{r study2 - exclusions}
ppt_excluded_completion_2 <- df.trial_raw_2 %>% 
  filter(is.na(count) & is.na(set_chosen)) %>%
  group_by(id) %>%
  summarise(n_no_count = n()) %>%
  filter(n_no_count > 1) %>%
  pull(id)

df.ppt_2 <- df.ppt_raw_2 %>%
  filter(!id %in% ppt_excluded_completion_2)

df.trial_precounted_2 <- df.trial_raw_2 %>%
  filter(!is.na(precounted))

df.trial_2 <- df.trial_raw_2 %>%
  filter(!id %in% ppt_excluded_completion_2) %>%
  filter(is.na(precounted))
```

```{r refactor}
df.trial_1 <- df.trial_1 %>% 
  mutate(knower_level_cp_subset = factor(knower_level_cp_subset, levels = c("subset", "CP")),
         magnitude = factor(magnitude, levels = c("small", "large")))

df.trial_2 <- df.trial_2 %>% 
  mutate(trial_type = factor(trial_type, levels = c("small", "large-DR", "large-NDR"), 
                             labels = c("small", "large-DR", "large-NR")))
```

```{r exp1 supplemental, fig.cap="Experiment 1: Histogram of participants’ performance in the Highest Count task, faceted by number of trials correct on the Correct Set Choice measure.", fig.width = 8, fig.height = 12, include = T}
ggplot(df.trial_1 %>%
         filter(!is.na(highest_count)) %>%
         group_by(id, knower_level_cp_subset, highest_count) %>%
         summarise(sum_correct_set_chosen = sum(correct_set_chosen)), 
       aes(x = highest_count, 
           fill = knower_level_cp_subset, 
           color = knower_level_cp_subset)) +
   geom_histogram(position = 'identity', 
                 alpha = 0.3, 
                 binwidth = 1) + 
  scale_fill_manual(values=cbPalette) + 
  scale_color_manual(values=cbPalette) + 
  facet_wrap(~sum_correct_set_chosen, 
             ncol = 2,
             scales = 'free') +
  scale_y_continuous(breaks = seq(0, 11, 1), 
                     limits = c(0, 11)) +
  scale_x_continuous(breaks = seq(0, 100, 10),
                     limits = c(0, 100)) +
   labs(y = "Number of participants", 
       x = "Highest Count", 
       color = "Knower Level", 
       fill = "Knower Level") + 
   theme(text = element_text(size = 13)) + 
  theme(legend.position = 'bottom')
```

```{r exp2 supplemental, fig.cap= "Experiment 2: Histogram of participants’ performance in the Highest Count task, faceted by number of trials correct on the Correct Set Choice measure.", fig.width = 10, fig.height = 12, include = T}
ggplot(df.trial_2 %>%
         filter(!is.na(highest_count)) %>%
         group_by(id, highest_count) %>%
         summarise(sum_correct_set_chosen = sum(correct_set_chosen)), 
       aes(x = highest_count)) +
   geom_histogram(position = 'identity', 
                 binwidth = 1, 
                 fill = cbPalette[2]) + 
  scale_fill_manual(values=cbPalette) + 
  scale_color_manual(values=cbPalette) + 
  facet_wrap(~sum_correct_set_chosen, 
             ncol = 3,
             scales = 'free') +
  scale_y_continuous(breaks = seq(0, 3, 1), 
                     limits = c(0, 3)) +
  scale_x_continuous(breaks = seq(0, 100, 10),
                     limits = c(0, 100)) +
   labs(y = "Number of participants", 
       x = "Highest Count") + 
   theme(text = element_text(size = 13)) 
```