% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  man,floatsintext]{apa7}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
\babelprovide[main,import]{english}
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% Table formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\centering\begin{threeparttable}}
%   {\end{threeparttable}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\centering\begin{ThreePartTable}}{\end{ThreePartTable}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% Overwrite redefinition of paragraph and subparagraph by the default LaTeX template
% See https://github.com/crsh/papaja/issues/292
\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries\itshape\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-\z@\relax}%
  {\normalfont\normalsize\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother

% \usepackage{etoolbox}
\makeatletter
\patchcmd{\HyOrg@maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\patchcmd{\HyOrg@maketitle}
  {\section{\protect\normalfont{\@title}}}
  {\section*{\protect\normalfont{\@title}}}
  {}{\typeout{Failed to patch title.}}
\makeatother

\usepackage{xpatch}
\makeatletter
\xapptocmd\appendix
  {\xapptocmd\section
    {\addcontentsline{toc}{section}{\appendixname\ifoneappendix\else~\theappendix\fi\\: #1}}
    {}{\InnerPatchFailed}%
  }
{}{\PatchFailed}
\keywords{number words, number concepts, exact equality, cardinal extension, language development, preschool children\newline\indent Word count: 12605}
\usepackage{csquotes}
\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-\z@\relax}%
  {\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother
\raggedbottom

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={The Development of Cardinal Extension: From Counting to Exact Equality},
  pdfauthor={Khuyen N. Le, Rose M. Schneider, \& David Barner},
  pdflang={en-EN},
  pdfkeywords={number words, number concepts, exact equality, cardinal extension, language development, preschool children},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{The Development of Cardinal Extension: From Counting to Exact Equality}
\author{Khuyen N. Le\textsuperscript{}, Rose M. Schneider\textsuperscript{}, \& David Barner\textsuperscript{}}
\date{}


\shorttitle{Cardinal Extension}

\authornote{

Part of these findings were presented as a poster at the 2024 Cognitive Development Society Biennial Meeting, and have been accepted as a talk at the 2024 Cognitive Science Society Meeting. The authors have no conflicts of interest to disclose. All materials, data, and analysis scripts are available at \url{https://osf.io/eswa4}. This research was funded by a National Science Foundation award (\#2000827) to DB.

Correspondence concerning this article should be addressed to Khuyen N. Le, Department of Psychology, University of California, San Diego, La Jolla, CA 92093-0109, United States. E-mail: \href{mailto:khuyenle@ucsd.edu}{\nolinkurl{khuyenle@ucsd.edu}}

}

\affiliation{\vspace{0.5cm}\textsuperscript{} {Department of Psychology, University of California, San Diego}}

\abstract{%
Numerate adults know that when two sets are equal they should be labeled by the same number word. We explored the development of this principle - sometimes called ``cardinal extension'' - and how it relates to children's other numerical abilities. Experiment 1 revealed that 2- to 5-year-old children who could accurately count large sets often inferred that two equal sets should be labeled with the same number word, unlike children who could not accurately count large sets. However, not all counters made this inference, suggesting that learning to construct and label large sets may be a necessary but not sufficient step in learning how numbers represent exact quantities. Experiment 2 found that children who extended labels to equal sets were not actually sensitive to exact equality, and that they also assigned two sets the same label when they were approximately equal, but differed by just 1 item (violating one-to-one correspondence). These results suggest a gradual, stage-like, process in which children learn to accurately count, learn to extend labels to perceptually similar sets, and then eventually restrict cardinal extension to sets that are exactly equal.

Public significance statement: This study suggests that learning to count and construct sets of large quantities may be a necessary but not sufficient step in learning how numbers represent exact quantities. While children who can accurately construct large sets show greater understanding that only sets of the same quantity can be labeled by the same number word, they also often assign the same number word to sets that are approximately equal.
}



\begin{document}
\maketitle

Imagine attending a lecture in an auditorium filled to capacity, where every seat is occupied by an eager student. After the lecture ends and everyone has left, you want to find out how many students attended. Is there a way to know? As numerate adults, we know that we can count the number of seats and then extend the resulting cardinal label (e.g., ``ten'') to the number of attendees. Understanding this principle, sometimes called ``cardinal extension'' (Muldoon et al., 2003), involves two distinct abilities. First, it requires the non-linguistic ability to recognize that two sets have the same number of items if and only if their members can be placed in one-to-one correspondence, sometimes called ``Hume's Principle'' (Boolos, 1986; Decock, 2008; Frege, 1880, 1884; Heck, 2000). Second, it requires understanding that a particular number word can be applied to two different sets if and only if they have an equal number of items. Therefore, cardinal extension integrates both non-linguistic reasoning about exact equality and linguistic knowledge of how number words encode number.

How do children acquire this knowledge? According to one view, once children learn their first 1-2 number words, they quickly infer that all number words denote unique, exact, numerosities. Previous studies establish that, beginning sometime after the age of 2, children learn the meanings of the words `one', `two', and `three' one at a time over the course of 1-2 years, during which time they are known as ``subset knowers'' (since they know the meanings of only a subset of numbers, e.g., Wynn, 1990, 1992). According to Sarnecka and Gelman (2004), knowledge of these first few number word meanings might be sufficient to support an inference that all number words denote unique, exact, numerosities, and therefore that sets which differ in number should receive different numerical labels, while equinumerous sets should receive the same labels. Further, they suggest that this should extend even to words for which these children don't yet have meanings. In support of this, they presented children who only knew words up to `three' with a large set - e.g., ``Look, there are five frogs'', and found that when an item was added to the set and children were asked ``Now are there five or six?'' they correctly chose the alternative label (similar results were also found for subtraction trials). Children also correctly reasoned that the number word should not change when a transformation does not change the quantity (e.g., when a set is simply rearranged). Other studies, however, have questioned these results, finding that children fail with highly similar tasks (Brooks et al., 2013; Condry \& Spelke, 2008; Sarnecka \& Wright, 2013). For example, when subset knowers are shown two sets that appear equal in number, are told that one of them contains, e.g., `six' things, and then see 1 item added to that set, they choose randomly between the two sets when asked to find the one with `six' (e.g., Brooks et al., 2013; Condry \& Spelke, 2008). Given such findings, some have argued that apparent successes may not demonstrate an understanding of how number words encode exact numerosities, but may instead reflect the use of a pragmatic inference compatible with the principle of contrast - i.e., that any referent that undergoes change along a meaning-relevant dimension should receive a new label (Brooks et al., 2013; see Izard et al., 2014 for a discussion).

According to an alternative hypothesis, children may not understand that number words denote unique, exact, numerosities until they understand how counting works, and are able to provide cardinal labels for any set they can count (Carey, 2004, 2009; Condry \& Spelke, 2008; Sarnecka \& Wright, 2013). Sometime after they learn the meanings of `one', `two', and `three', children appear to discover that counting can be used to both construct large sets and label their cardinalities, at which point they are sometimes called ``Cardinal Principle'' knowers (or CP knowers). For example, in Wynn's Give-a-Number task, when CP knowers are given a pile of objects, like fish, and asked to give ``five fish'', they are typically able to count and give the requested number, unlike subset knowers. According to some proposals, it is this ability to accurately count and construct large sets that establishes children's understanding of how number words represent cardinality, since mastery of counting requires establishing one-to-one correspondence between labels and counted objects, which in turn guarantees that any two counts to a particular number - like five - will result in the same number (Carey, 2004, 2009). As evidence for this, previous studies have found that CP knowers outperform subset knowers in tests of cardinal extension. For example, when shown two sets that appear equal in number, CP knowers often correctly judge that if a number word, e.g., `five,' applies to one set, it should also apply to the other, while subset knowers fail at the same task (Sarnecka \& Gelman, 2004; Sarnecka \& Wright, 2013). Similarly, when shown a set of items that is labeled with a number word, e.g., `four turtles', and asked to distinguish between two sets to find a set with the same number word label, CP knowers, but not subset knowers, succeed (Slusser \& Sarnecka, 2011). These findings suggest that learning to accurately count and construct large numbers is related to a qualitative change in children's understanding of how number words encode exact equality.

While CP knowers are able to accurately count and label large sets, some have suggested that these abilities may actually reflect rote procedures (Davidson et al., 2012), and that many CP knowers still don't understand that every number word denotes a unique cardinality, or that equinumerous sets should receive the same cardinal label. Instead, they have argued that this knowledge may emerge after children become CP knowers (for discussion see Schneider et al., 2022). As evidence for this, although CP knowers outperform subset knowers on tests of cardinal extension, they rarely perform at ceiling, failing from 15\% to 40\% of the trials depending of the task (Sarnecka \& Gelman, 2004; Sarnecka \& Wright, 2013; Slusser \& Sarnecka, 2011). In fact, multiple past studies report variability on tests of cardinal extension until up to 5 years of age. However, in many cases these studies have not classified children's knower levels, leaving open the role of counting knowledge in children's performance. For example, in one study, Muldoon et al. (2005) showed 3- and 4-year-olds a set of lions who rode their bicycles to school and then disappeared inside it. Children were first asked how many bicycles there were -- which they were able to count. They were then asked how many lions there were, to probe whether they can infer the number of a hidden set (the lions) from the number of a visible set in one-to-one correspondence (the bicycles), without having to count the lions. When the number of items was large (5 to 6 items), 3-year-olds extended the label of the visible set to the hidden set about 56\% of the time, while 4-year-olds succeeded about 86\% of the time (see also Sophian et al., 1995 for similar results with 5-year-olds\footnote{Children were more successful at this task when the sets were small (2-3 items) -- 3-year-olds succeeded 87\% of the time and 4-year-olds 91\% of the time. However, this might be due to children subitizing the sets while they were visible, memorizing the number of items of the hidden sets, and reporting it once asked.}). In another study, Frydman and Bryant (1988) found that when two equal sets were generated through sharing, fewer than half of the 4-year-olds tested were able to infer the cardinality of one set by counting the other set. Similarly, Muldoon et al. (2003) asked 3.5 to 5-year-olds to construct a set equivalent to a set they had already counted, and to judge whether a new set that was one-too-many or one-too-few had the same number of items as the counted set. They found that roughly half of children succeeded in these tasks (ranging from 43\% - 65\% depending on the task).

Adding to doubt that children master cardinal extension when they become CP knowers is the fact that such children often fail on tasks that test non-verbal understanding of one-to-one correspondence. First, classic Piagetian studies of conservation show some degree of difficulty in children well past the age of 5, though subsequent studies argued that such failures might be explained by alternative factors. For example, similar to the Brooks et al. (2013)'s pragmatic account of Sarnecka and Gelman (2004), some have argued that repeatedly asking children the same question about a referent set (``Which line has more?'') may lead them to infer that a new response is required, and that they should therefore base their judgment on the property that changed (e.g., line length), rather than on number (McGarrigle \& Donaldson, 1974; Mehler \& Bever, 1967; Rose \& Blank, 1974). However, other studies have nevertheless found continuing failures in children as old as 6 on tasks that reduce these demands (Piaget, 1965; Russac, 1978; Schneider et al., 2022). For example, using tasks similar to those used in tests of non-numerate groups like the Piraha and Mundurucu (Gordon, 2004; Pica et al., 2004), Schneider et al. (2022) presented children with a row of fish and asked them to match that row. Although both subset knowers and CP knowers performed better than chance when tested with small sets (e.g., 3), only CP knowers were better than chance for large sets, but many failed to provide exact matches, instead approximating. This was true even when children were explicitly asked to match the number, and when the task was presented as a sharing game where their goal was to ensure fairness in how fish were distributed to two penguins. Although some studies have shown precursors to one-to-one correspondence in younger children (Izard et al., 2014), here too success is limited to cases in which children can make judgments based on small sets\footnote{In Izard et al. (2014), children continued searching when 3 puppets were presented on 3 branches, then were hidden in a box, and 2 were removed from the box. They also succeeded when 6 puppets were presented on 6 branches, and 5 came out. However they failed when 6 puppets were presented on 11 branches and 5 came out, suggesting that their success in the 5/6 case was driven by their ability to track a small number of empty branches, not their ability to track 5 objects.}.

To summarize, previous studies have debated when and how children acquire the two core components of cardinal extension - i.e., that two equal sets should receive the same label, and that two sets are equal only if their elements stand in one-to-one correspondence. Some argue that this knowledge emerges after children learn just 1-2 small number words, while others argue that it develops when children become CP knowers, or even sometime after this. Critically, however, previous studies are limited in various ways that make it difficult to know how such knowledge actually arises. First, some studies test cardinal extension and find variability between the ages of 3 and 5, but do not classify children into knower levels, making it difficult to know how their performance relates to knowledge of counting (e.g., Frydman \& Bryant, 1988; Muldoon et al., 2003, 2005; Sophian et al., 1995). Second, other studies have classified children as subset knowers or CP knowers and tested differences between these groups, but have not analyzed sources of individual differences between children within these groups (e.g., Sarnecka \& Gelman, 2004; Sarnecka \& Wright, 2013; Slusser \& Sarnecka, 2011). Third, as we explain below, while cardinal extension requires two components (recognizing equinumerous sets and understanding that such sets share the same number label), previous studies typically test only one or the other, but rarely test both.

Crucially, most studies that attempt to test both children's reasoning about equinumerosity and how they use this knowledge to extend number labels (e.g., Sarnecka \& Gelman, 2004) do not differentiate between reasoning about exact vs.~approximate representations of number\footnote{One study, Sophian et al. (1995), did include trials that could differentiate between an exact equality vs.~approximate quantity strategy, but did not report separate trial performance.}. This is important, because children might represent two sets as ``the same'' using approximate representations of number, even if the sets violate one-to-one correspondence and differ by 1 item\footnote{As already noted, one exception to this is Sarnecka and Gelman (2004), which found that subset knowers who extend number words to two equal sets subsequently refuse to do so after an object is added to one of them. However, in addition to conflicting with results from other tasks, this study did not test whether children's change in judgment was due to a violation of one-to-one, or the more general pragmatic heuristics that ``a change in number should reflect a change in number word'', which is neutral with respect to whether - and how - children represent the sets as equal (Brooks et al., 2013).}. A large literature indicates that human perception of large sets is supported by representations in the Approximate Number System (ANS, Cordes et al., 2001; Dehaene, 1997, 2009; Feigenson et al., 2004; Whalen et al., 1999) such that sets that differ by large ratios - e.g., 2:1, 2:3 - are easy to discriminate, while sets with smaller ratios often are not. Although the acuity of this system improves with age (Halberda \& Feigenson, 2008; Huntley-Fenner \& Cannon, 2000), even adults often fail to reliably discriminate large sets that have a ratio less than 7:8. Meanwhile, accurate and adult-like set comparison for sets beyond the subitizable range with perceptually non-discriminable ratios requires precise representations of numerosities (see Feigenson et al., 2004 for a discussion). Consequently, in order to be sure that children extend number words to sets that are exactly equal, it's critical to ensure that their extension is not based on approximate matches between sets. While some studies have attempted to do this by showing children two equal sets and then adding or subtracting 1 item from one set (e.g., Sarnecka \& Gelman, 2004), in such studies children might assume that any change in number requires a change in label without knowing how to assess equality, and also without thinking that this principle of contrast is specific to number (see, e.g., Brooks et al., 2013, for evidence that children make identical patterns of inference for changes in an object's part-whole structure).

The present studies aimed to address the limitations of past reports. Adapting the animal-bicycle task from Muldoon et al. (2005) in Experiment 1, we presented subset knowers and CP knowers with two sets of animals in unequal numbers - 5 bunnies and 7 lions. Animals in each group carried items (e.g., the bunnies had blue hats and the lions had red hats), such that the number of items was exactly equal to the number of animals in each group. The animal sets were then hidden, and children were prompted to infer the number of one of the two hidden animal sets (e.g., the number of bunnies). We reasoned that if children believe that two equal sets deserve the same numerical label, they should count the correct visible objects to infer the number of hidden objects (e.g., counting the bunnies' hats to infer the number of bunnies). In Experiment 2, we probed the nature of the numerical representations used by children who appeared to succeed at cardinal extension, by asking whether they reasoned about exact equality or approximate magnitudes. In addition to exploring differences in performance between CP- and subset knowers, we also investigated children's age and familiarity with counting as possible factors explaining variability within each knower level group.

\hypertarget{experiment-1}{%
\section{Experiment 1}\label{experiment-1}}

\hypertarget{method}{%
\subsection{Method}\label{method}}

\hypertarget{participants}{%
\subsubsection{Participants}\label{participants}}

A preregistration is available at \url{https://osf.io/3v2cn}.
Eighty-four\footnote{We recruited four more CP knowers than preregistered due to an initial knower-level coding error.} children were recruited from preschools in the US and Canada, and a children's museum in the US.
All participants spoke English as a primary language. Based on preregistered criteria, we excluded two participants who did not provide a response for more than one trial of the Cardinal Extension task, and two trials due to experimenter error. Our final sample included 82 children, with 38 subset knowers (23F, 15M; \(M_{age}\) = 3.55 {[}2.13; 5.20{]}; \(SD_{age}\) = 0.76)
and 44 CP knowers (25F, 19M; \(M_{age}\) = 4.63 {[}3.08; 5.95{]}; \(SD_{age}\) = 0.65). The sample size was determined with an \emph{a priori} power analysis on G*Power version 3.1.9.6 (Faul et al., 2009), and is adequate to achieve 80\% power for detecting a medium effect, at a significance criterion of \(\alpha\) = 0.05 for a linear regression with 3 predictors (Age, Knower Level, and Set Size). This study was approved by the UCSD Human Research Protections Program (Protocol \#200520).

\hypertarget{material-procedure}{%
\subsubsection{Material \& Procedure}\label{material-procedure}}

All materials, data, and analysis code for the experiment are available at \url{https://osf.io/eswa4}.

\hypertarget{give-n}{%
\paragraph{Give-N}\label{give-n}}

Participants were given a titrated Give-N task (following the procedure in Wynn, 1992) to classify them as either subset knowers or CP knowers. Participants were shown a box with fish and a plate, and were asked to ``put N fish on the plate.'' All participants started with `five', and received increasingly larger numbers (N+1, up to `six') if they succeeded and smaller numbers (N-1) if they failed. If the child gave the wrong number, they were prompted once to ``count to make sure'' and were allowed to fix their response. We recorded the largest number for which the child gave correct responses on at least two out of three trials. We excluded children who could not construct sets of `one' on at least two out of three trials. Children who succeeded on sets of `five' or `six' on at least two out of three trials were designated as CP knowers, and those who only succeeded on smaller numbers (e.g., `one', `two', `three', `four') were designated as subset knowers.

\hypertarget{cardinal-extension}{%
\paragraph{Cardinal Extension}\label{cardinal-extension}}

Materials were prepared and presented as a slidedeck with recorded audio descriptions. Participants were first introduced to the animals used in the task (lions and bunnies). They then saw two familiarization trials with three animals, in which each animal was associated with one item (e.g., each bunny had a bike). They were then asked to report the number of animals by pointing to the screen and counting to familiarize them with the expectations for critical trials.

In each critical trial (Figure \ref{fig:exp1-figure}), participants saw two unequal groups of animals (e.g., 5 bunnies and 7 lions), each on one side of the screen. Initially, each animal was physically connected to one item (e.g., each animal wore a hat), such that animals and items stood in one-to-one correspondence (e.g., 5 bunnies -- 5 blue hats vs.~7 lions -- 7 red hats). Each group of animals stood with their items in a vertical line with equal spacing to facilitate element tracking and counting. The animals then put down their items and disappeared into a school. Participants were then asked for the number of one set of animals (e.g., ``How many bunnies are in the school?''). If participants gave a response without counting, they were encouraged to `point and count' (the experimenter never specified what they should count). Out of 27 total trials, there were 25 trials where CP knowers responded with a number but did not count (small sets: 14; large sets: 11), and there were 83 trials where subset knowers responded with a number but did not count (small sets: 43; large sets: 40). If counting resulted in a different response, we analyzed the final count. Participants were allowed one opportunity to fix a wrong response.

Participants saw six critical trials in total: three small-set trials where sets were less than 4 (1:2, 1:3, 2:3), and three large-set trials where sets were greater than 4 (5:7, 5:8, 6:7). Lions and bunnies were used for all trials, but they carried different kinds of items for each trial. Participants saw one out of six pseudo-randomized trial orders. Trials were counterbalanced for the target animals, side of set appearance, and which animal set is larger.

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth]{figs/exp1} 

}

\caption{Schematic of Experiment 1. Slides are presented in order, from left to right and top to bottom. The corresponding audio description is under each slide.}\label{fig:exp1-figure}
\end{figure}

\hypertarget{highest-count}{%
\paragraph{Highest Count}\label{highest-count}}

This task was included as a general proxy of counting experience, to allow us to differentiate between CP knowers with different degrees of counting training. Participants were asked to ``count as high as you can,'' beginning from one. The experimenter prompted them with `one' (but no other number) if they failed to respond, and they were prompted once after they stopped to keep counting. We recorded the highest number they reached without errors.

\hypertarget{transparency-openness}{%
\subsubsection{Transparency \& Openness}\label{transparency-openness}}

All materials, data, and analysis code for both Experiments 1 and 2 are available at \url{https://osf.io/eswa4}. Data were analyzed using R (Version 4.1.3, R Core Team, 2022) and the R-packages \emph{lme4} (Bates et al., 2015), \emph{car} (Fox \& Weisberg, 2019), \emph{emmeans} (Lenth, 2023), \emph{ggplot2} (Wickham, 2016), \emph{cowplot} (Wilke, 2024), \emph{tidyverse} (Wickham et al., 2019), and \emph{papaja} (Aust \& Barth, 2022). The design and analysis of both experiments were preregistered, and we report how we determined our sample size, all data exclusions, all manipulations, and all measures in the study.

\hypertarget{results}{%
\subsection{Results}\label{results}}

Our primary question was whether CP knowers were more likely to succeed at the Cardinal Extension task compared to subset knowers across both small and large sets. To test this, we asked whether children knew that to find the number of animals in the school (e.g., bunnies), they should count the items that these animals left outside the school (and which were therefore equal in number) - what we describe below as Correct Set Choice. To identify children who selected the correct set, we coded two kinds of response as correct. First, we credited the child with a correct response if they counted the correct set. We counted these responses as correct even if they attempted the attempted count resulted in an incorrect response in order to recognize that some children might have an understanding that two equal sets deserve the same label but nevertheless make procedural counting errors (e.g., in the case of some CP knowers). Also, this allowed for the possibility, proposed by Sarnecka and Gelman (2004), that a subset knower might know that two large sets should receive the same label if they are equal, but might not be able to say how many items the sets actually contain (because they can't yet count). Second, we also credited the child with a correct response if, despite not attempting to count, they nevertheless provided a correct numerical response. Here, we reasoned that such a response is most likely if the child has successfully identified the correct item set from which to infer the number of animals.

We also included a secondary analysis to explore how often children provided a correct numerical response overall. Although children might understand cardinal extension while still making counting errors, it is nevertheless interesting to know how often children were able to provide the correct numerical response and were therefore fully adult-like (e.g., by choosing the right side, and accurately counting the available items). For this measure, we credited children with success if they provided the correct numerical response whether or not they pointed to the screen as part of obtaining their answer. However, if children clearly counted the wrong set (or both sets) and got the correct answer through a counting error, they were not credited with success. We will refer to this measure as `Correct Numerical Response' in the following analysis.

First, we consider the `Correct Set Choice' measure. Overall, CP knowers were more likely than subset knowers to choose the correct set to count for both small and large sets (see Table \ref{tab:table1} for statistical results).
Two-tailed one-sample t-tests found that only CP knowers (\(M\) = 0.88, \(SD\) = 0.32) performed better than chance at identifying the correct item set to infer the number of hidden animals (\(t(261) = 19.09\), \(p < .001\)), and they succeeded for both small and large sets (\(p\)s \textless{} .001). Meanwhile, subset knowers (\(M\) = 0.49, \(SD\) = 0.50) performed at chance (\(t(227) = -0.40\), \(p = .692\)), and failed to identify the correct set for both small and large sets (\(p\)s \textgreater{} .05).
However, despite their above-chance performance we found substantial variability in CP knowers' performance: out of 44 CP knowers, only 26 (59.09\%) succeeded in identifying the correct set (either by attempting to count the correct set, or giving the correct numerical response without counting) in all six trials (binomial \(p\) \textless{} .05). Three CP knowers (6.82\%) succeeded in only half of the trials or fewer.

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:table1}Results of t-tests comparing cardinal extension performance between subset- and CP knowers.}

\begin{tabular}{llllllll}
\toprule
 & \multicolumn{2}{c}{subset} & \multicolumn{2}{c}{CP}  &  &  &\\
\cmidrule(r){2-3} \cmidrule(r){4-5}
Cardinal extension performance & \multicolumn{1}{c}{M} & \multicolumn{1}{c}{SD} & \multicolumn{1}{c}{M} & \multicolumn{1}{c}{SD} & \multicolumn{1}{c}{t} & \multicolumn{1}{c}{df} & \multicolumn{1}{c}{p}\\
\midrule
Correct Set Choice &  &  &  &  &  &  & \\
\ \ Small sets & 0.51 & 0.50 & 0.89 & 0.50 & 6.89 & 186.58 & < .001\\
\ \ Large sets & 0.46 & 0.50 & 0.88 & 0.50 & 7.51 & 190.31 & < .001\\
\ \ Total & 0.49 & 0.50 & 0.88 & 0.50 & 10.19 & 378.41 & < .001\\
Correct Numerical Response &  &  &  &  &  &  & \\
\ \ Small sets & 0.48 & 0.50 & 0.89 & 0.50 & 7.37 & 186.64 & < .001\\
\ \ Large sets & 0.16 & 0.37 & 0.74 & 0.37 & 11.31 & 242.54 & < .001\\
\ \ Total & 0.32 & 0.47 & 0.81 & 0.47 & 12.55 & 444.06 & < .001\\
\bottomrule
\addlinespace
\end{tabular}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} Performance for each trial is coded as follows. For ‘Correct Set Choice’, 1: attempted to count the correct set (regardless of correct or incorrect numerical response), or provided the correct numerical response without counting, 0: counted the wrong set or both sets, or provided the wrong numerical response without counting. For ‘Correct Numerical Response,’ 1: provided the correct numerical response (by counting the correct set or without counting at all), 0: provided the wrong numerical response, or counted the wrong set or both sets (even if the right numerical response was reached through a counting error).}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}

In order to further analyze the effect of CP knowledge on cardinal extension performance as measured by Correct Set Choice, we constructed a generalized linear mixed-effects models (GLMM) with the formula Correct Set Choice (0/1) \textasciitilde{} Age (z-scored) + Set Size (Small / Large) + (1 \textbar{} Participant) + (1 \textbar{} Trial), and tested whether adding children's Knower Level (CP / Subset) and Knower Level * Set Size interaction improved the fit of the model. All models included by-subject and by-item random intercepts.
Our base model showed a significant effect of age (\(\beta\) = 1.67, 95\% CI = {[}1.14, 2.19{]}, \(p < .001\)), with older children performing better than younger children. However, set size (small vs large sets) did not further explain variation in performance (\(p = .504\)). Exploratory models analyzing subset knowers and CP knowers separately showed that this age effect was driven by only subset knowers (\(\beta\) = 1.56, 95\% CI = {[}0.85, 2.26{]}, \(p < .001\)). Age did not predict performance in the CP knower group (\(p = .210\)). Adding Knower Level as a predictor significantly improved the fit of the model (\(\chi^2\)(1) = 6.98, \(p = .008\)), and revealed that CP knowers were significantly more likely than subset knowers to select the correct set, even when controlling for age (\(\beta\)\(_{CP}\) = 1.43, 95\% CI = {[}0.37, 2.50{]}, \(p = .008\)). This model also showed a significant effect of age (\(\beta\) = 1.18, 95\% CI = {[}0.61, 1.75{]}, \(p < .001\)) but not of set size (\(p = .501\)). These main effects are illustrated in Figure 2A. Adding Knower Level * Set Size interaction did not further improve the model (\(p = .663\)).

\begin{figure}
\centering
\includegraphics{2_writeup_files/figure-latex/exp1-plot-1.pdf}
\caption{\label{fig:exp1-plot}Each dot represents a participant. The width of the shaded area of violin plots represents the proportion of the data located there. A) Proportion of correct item set choice by participant against knower level. Horizontal dashed line indicates performance at chance = 0.50. B) Proportion of correct numerical response by participant against knower level.}
\end{figure}

We next asked how often participants gave the correct numerical response. Here we expected subset knowers would fail for large sets (since they generally can't count accurately), and to sometimes succeed for smaller ones, and for CP knowers to perform better in both cases. Compatible with these expectations, Welch two-tailed two-sample t-test found that CP knowers provided the correct number of the hidden animal set more than subset knowers in both small and large sets (Table \ref{tab:table1}). We again observed variability in CP knowers' performance: out of 44 CP knowers, only 18 (40.91\%) succeeded in providing the correct numerical response for all six trials. Five CP knowers (11.36\%) succeeded in only half of the trials or fewer.
Among CP knowers, some of these failures were due to procedural counting errors: out of 46 trials where CP knowers gave the wrong numerical response, on 18 trials (36.73\%) they counted the correct item set but made a mistake in their count (even though we gave them one chance to fix their wrong count).
On 13 trials (26.53\%), they counted the wrong item set, or both item sets, which pointed to a lack of cardinal extension understanding. Finally, on the remaining 15 trials (30.61\%), CP knowers provided the wrong numerical response without pointing to items in either visible set - a behavior compatible either with overconfidence in their ability to accurately estimate a set size, an attempt to count without pointing, or a failure to understand that the target number could be obtained by counting one of the visible sets.

To further explore the effect of CP knower status on Correct Numerical Response, we constructed another set of GLMMs with the same fixed and random effect structure as the first analytical approach to predict children's ability to infer the correct number of animals. Specifically, our base model had the formula Correct Numerical Response (0/1) \textasciitilde{} Age (z-scored) + Set Size (Small / Large) + (1 \textbar{} Participant) + (1 \textbar{} Trial), and we tested whether adding children's Knower Level (CP / Subset) and Knower Level * Set Size interaction improved the fit of the model. The model that best explained the data included Age, Knower Level, Set Size, and Knower Level * Set Size interaction as predictors (compared against base model with only Age and Set Size: \(\chi^2\)(2) = 20.34, \(p < .001\); compared against model with Age, Set Size and Knower Level: \(\chi^2\)(1) = 4.77, \(p = .029\)). CP knowers were significantly better at determining the correct number of animals (\(\beta\)\(_{CP}\) = 1.53, 95\% CI = {[}0.27, 2.78{]}, \(p = .017\)), as were older children (\(\beta\) = 1.15, 95\% CI = {[}0.55, 1.76{]}, \(p < .001\)). We also found an effect of Set Size with children more likely to provide the correct numerical response in trials with small sets compared to those with large sets (\(\beta\)\(_{large}\) = -2.59, 95\% CI = {[}-3.66, -1.52{]}, \(p < .001\)). Additionally, the Knower Level * Set Size interaction effect was significant, where subset knowers showed a larger difference in performance between small and large trials compared to CP knowers (\(\beta\)\(_{CP*large}\) = 1.28, 95\% CI = {[}0.11, 2.45{]}, \(p = .032\)). These effects are illustrated in Figure 2B.

As an exploratory analysis, we investigated whether children's Highest Count explained further variability in our data, by adding it as a fixed effect to the best-performing models from the two analysis approaches above. Seventy-eightchildren (out of 82) provided a Highest Count, so we refitted our best-performing models to only the data from these children. Adding Highest Count did not explain additional variation for either approach (Correct Set: \(\chi^2\)(1) = 0.06, \(p = .805\); Correct Numerical Response: \(\chi^2\)(1) = 0.30, \(p = .584\)). When we limited this analysis to only CP knowers, Highest Count also did not explain additional variation in the observed performance (\(p\)s \textgreater{} .05).

\hypertarget{discussion}{%
\subsection{Discussion}\label{discussion}}

Experiment 1 found three main results. First, CP knowers often chose the correct set to determine how many animals were hidden, compatible with some preliminary understanding of cardinal extension, while subset knowers completely failed. Second, although many CP knowers succeeded at this task, many also failed. Third, we found that many children failed to provide a correct numerical label, which could reflect a failure to understand cardinal extension, a lack of counting knowledge (e.g., in subset knowers), procedural counting errors, or a decision to not attempt to count during the task. Together, these results suggest that children do not acquire an understanding of cardinal extension prior to the CP-stage, and therefore that knowledge of just 1-2 number words is not sufficient to support this ability. Similarly, due to the variability in performance even among CP knowers, the data suggest that full mastery of cardinal extension likely emerges sometime after children learn to accurately count large sets.

Although we found that CP knowers appeared to demonstrate some understanding of cardinal extension, Experiment 1 may still overestimate the number of children who grasp this principle for two reasons. First, in Experiment 1 - as in studies that use a similar design such as Muldoon et al. (2005) and Sophian et al. (1995) - children may have deployed a simple heuristic to choose the appropriate set that did not rely on understanding of cardinal extension. In particular, because there were two sets of animals, each with their own items, when children were asked, e.g., how many bunnies were in the school, they might have chosen to count the bunnies' items based purely on the association between these animals and their items, but not based on their equinumerosity. Second, although animals and their target items in Experiment 1 were equal in number, this does not guarantee that children actually used this information as the basis for their judgments. Instead, as noted in the Introduction, it is possible that they chose which set to count based on its approximate match to the hidden set. We addressed these questions in Experiment 2.

\hypertarget{experiment-2}{%
\section{Experiment 2}\label{experiment-2}}

Experiment 1 found that many CP knowers infer that sets which appear equal in number can be labeled by the same number word. However, the study left open how children arrive at this conclusion. One possibility is that they select the correct set by noticing a one-to-one correspondence between items and animals, and reasoning that because the two sets are equal they deserve the same label (e.g., exactly 5 bunnies and exactly 5 hats). Alternatively, they might compare only the approximate quantity of these sets (e.g., approximately 5 bunnies and approximately 5 hats). Finally, another possibility is that they might succeed by merely noting the association between the correct item set and the target animal set (e.g., the bunnies appear on the left, therefore choose the item set on the left; or the bunnies have blue hats, therefore choose the blue hats), without attending to cardinality at all.

To probe whether children use exact or approximate representations to support cardinal extension, and to eliminate the possibility of using identity associations between animals and items, in Experiment 2 we paired one animal set with two item sets in varying ratios. One item set exhibited one-to-one correspondence with the animal set, and thus could be counted to infer the number of animals once hidden. The distractor item set either differed from the animal set in a perceptually discriminable ratio (e.g., 5 hats : 10 bunnies), or were off by one in quantity and were not discriminable according to their ratio (e.g., 9 hats : 10 bunnies). This design prevented children from attending to the item/animal identity as a strategy to solve the task. Additionally, it differentiated two set comparison strategies. If CP knowers succeed in cardinal extension through reasoning about one-to-one correspondence and exact set equality, they should succeed in both cases. However, if they only attend to approximate quantities, they should succeed in trials with discriminable ratios, but not in the off-by-one trials.

\hypertarget{method-1}{%
\subsection{Method}\label{method-1}}

\hypertarget{participants-1}{%
\subsubsection{Participants}\label{participants-1}}

A preregistration is available at \url{https://osf.io/zrsw2}.
Eighty children were recruited from preschools and a children's museum in the US. Given the failure of subset knowers in Experiment 1, all participants were CP knowers who spoke English as a primary language. We excluded two participants who missed more than one trial of the Cardinal Extension task based on preregistered criteria. We also excluded 18 trials where participants started counting the animals before the prompt, to ensure we only analyzed numerical responses from participants who attempted to make the inference after the animal set was hidden. Our final sample included 80 CP knowers (44F, 36M; \(M_{age}\) = 4.67 {[}3.29; 5.98{]}; \(SD_{age}\) = 0.70). The sample size was determined with an \emph{a priori} power analysis on G*Power version 3.1.9.6 (Faul et al., 2009), and is adequate to achieve 80\% power for detecting a medium effect, at a significance criterion of \(\alpha\) = 0.05 for a linear regression with 2 predictors (Age and Trial Type). This study was approved by the UCSD Human Research Protections Program (Protocol \#200520).

\hypertarget{material-procedure-1}{%
\subsubsection{Material \& Procedure}\label{material-procedure-1}}

All materials, data, and analysis code for the experiment are available at \url{https://osf.io/eswa4}.

\hypertarget{give-n-1}{%
\paragraph{Give-N}\label{give-n-1}}

Participants were given a Give-N task and a Highest Count task following the procedure from Experiment 1. In order to be confident that the children in this study were CP knowers, we used a more conservative criterion for CP status than in Experiment 1, and classified children as CP knowers only if they succeeded at constructing sets of ``six'' two out of three times on the Give-N task. Children who did not meet this criterion did not proceed to the Cardinal Extension task.

\hypertarget{cardinal-extension-1}{%
\paragraph{Cardinal Extension}\label{cardinal-extension-1}}

Materials and procedure were similar to Experiment 1, with any differences noted. In the familiarization phase, participants saw an additional trial with three animals (in this study, only bunnies), but only two of them had items and one of them did not. The bunny missing an item was highlighted to the participant (``This bunny doesn't have a carrot''). This was done to highlight the violation of one-to-one correspondence, to be sure that any child who failed at the task did so despite noticing violations of one-to-one. Participants were also asked to point and count the number of bunnies for this trial.

In each critical trial (Figure \ref{fig:exp2-figure}), a set of bunnies appeared at the bottom of the screen with two sets of items. One set of items (the target set) was exactly equal to the number of bunnies, and the other set (the distractor set) had fewer items (e.g., 11 bunnies with 11 hats and 5 water bottles). The audio description highlighted the violation of one-to-one correspondence between the distractor set and the set of bunnies (e.g., `Some of the bunnies don't have their water bottles'). The experimenter also gestured to the bunny or bunnies missing any item. The bunnies then put down each item in each set one at a time (e.g., each bunny put down their hat, then each of the bunnies with backpacks put down their backpack), to further emphasize the one-to-one correspondence between the bunnies and the target set, and reiterate the mismatch with the distractor set. Like in Experiment 1, the bunnies then disappeared into a building, leaving their items behind. Participants were then asked for the number of bunnies, following the same procedure as described in Experiment 1. Here, like Experiment 1, sometimes participants gave a response without counting, despite being encouraged to `point and count'. Out of 684 total trials, there were 103 trials where CP knowers responded with a number but did not count (small trials: 32; large trials with perceptually discriminable ratios: 35; large trials with off-by-one difference: 36).

Participants saw nine trials in total: three small-set trials where sets were less than 4 (1:2, 1:3, 2:3), and six large-set trials where sets were greater than 4. Large-set trials included three with discriminable ratios (Large-DR: 5:10, 5:11, 6:12) where the ratio between the bunnies and the distractor item set was at least 2:1, and three with non-discriminable ratios (Large-NR: 9:10, 10:11, 11:12) where the distractor set had one fewer item than the number of bunnies. Participants saw 1 of 4 pseudo-randomized trial orders and item pairings. The trials were partially-counterbalanced for order and location of item sets.

\begin{figure}[h]

{\centering \includegraphics[width=1\linewidth]{figs/exp2} 

}

\caption{Schematic of Experiment 2. Slides are presented in order, from left to right and top to bottom. The corresponding audio description is under each slide.}\label{fig:exp2-figure}
\end{figure}

\hypertarget{results-1}{%
\subsection{Results}\label{results-1}}

Our primary questions were (1) whether children chose the correct set to infer the number of bunnies across trials of different set sizes and ratios, and (2) whether children who did this drew on one-to-one correspondence or approximate number representations as the basis for their judgments. Similar to the analysis for Experiment 1, we first examined whether children made the Correct Set Choice. Two-tailed one-sample t-tests showed that overall performance was better than chance (\(t(683) = 10.17\), \(p < .001\)).
However, this was only true for small trials (\(M\) = 0.81, \(SD\) = 0.39; \(t(228) = 12.07\), \(p < .001\)) and large trials with perceptually-disciminable ratios (\(M\) = 0.69, \(SD\) = 0.46; \(t(225) = 6.34\), \(p < .001\)). In large trials with an off-by-one difference (\(M\) = 0.54, \(SD\) = 0.50), children performed at chance overall (\(t(228) = 1.12\), \(p = .262\); Figure 4A). Out of 80 children tested, only 17 (21.25\%) succeeded in all trials, showing some evidence of using one-to-one correspondence in extending number words\footnote{On average, these 17 children were slightly older and had a greater Highest Count score (\(M_{age}\) = NA; \(M_{HC}\) = NA) compared to children who did not succeed in all trials (\(M_{age}\) = 4.67; \(M_{HC}\) = 25.82), though due to the small number of children we could not compare these values. Note that one of these 17 children only contributed 4 trials (2 small trials, 1 large trial with perceptually-discriminable ratio, and 1 large trial with an off-by-one difference) because they began counting the bunnies before the animals disappeared on the other 5 trials. However, this child was included because they selected the correct set on all 4 of the trials they contributed, including the large trial with an off-by-one difference. Similarly, another one of these 17 children had 1 large trial with perceptually-discriminable ratio omitted due to precounting, but succeeded in all other 8 trials.}.
An additional 4 children succeeded in all large trials with an off-by-one difference, but made at least one mistake in the other trials.

\begin{figure}
\centering
\includegraphics{2_writeup_files/figure-latex/exp2-plot-1.pdf}
\caption{\label{fig:exp2-plot}Each dot represents a participant. The width of the shaded area of violin plots represents the proportion of the data located there. A) Proportion of correct item set choice by participant against trial type. Horizontal dashed line indicates performance at chance = 0.50. B) Proportion of correct numerical response by participant against trial type.}
\end{figure}

To further analyze the effect of trial type on selection of the Correct Set Choice, we constructed a GLMM with the formula Correct Set Choice (0/1) \textasciitilde{} Age (z-scored) + (1 \textbar{} Participant) + (1 \textbar{} Trial), and tested whether adding Trial Type (Small / Large with perceptually discriminable ratios (Large-DR) / Large with an off-by-one difference (Large-NR)) as fixed effects improved the fit of the model. All models included by-subject and by-item random intercepts. We found no effect of age in our base model (\(p = .076\)). When trial type was included as a fixed effect, we found a significant effect of trial type (\(\chi^2\)(2) = 40.78, \(p < .001\)), and still no effect of age (\(p = .078\)). The model with Trial Type explained significantly more variation in the observed data compared to the base model in a likelihood ratio test (\(\chi^2\)(2) = 16.97, \(p < .001\)). This finding replicated our finding from Experiment 1, which found that age did not explain cardinal extension performance in CP knowers. \emph{Post hoc} pairwise comparisons between the three trial types (Small, Large-DR, Large-NR) with Bonferroni correction found that children were more likely to succeed in Small trials compared to Large-DR trials (\(z\) = 3.09, \(p = .006\)) and Large-NR trials (\(z\) = 6.34, \(p < .001\)). Success in Large-DR trials was also significantly higher than in Large-NR trials (\(z\) = 3.75, \(p < .001\)).

We conducted an exploratory analysis evaluating children's errors in choosing the correct set. Specifically, we reasoned that if children failed at large trials with an off-by-one difference (Large-NR) because they only attended to approximate quantities (choosing randomly between the two sets when they were off-by-one), then they should select the wrong set more often in such trials compared to large trials with discriminable ratios (Large-DR). Meanwhile, the rate of other error types, e.g., not choosing any set or attempting to count both sets, should be equal across Large-NR and -DR trials (see Table \ref{tab:table2} for descriptive statistics). We performed a chi-square test of independence to examine the relation between error types (choosing the distractor set / choosing both sets / not choosing any set) and trial types (Large-DR / Large-NR), and found that there was a significant association between these variables, \(\chi^2(2) = 14.60\), \(p < .001\). \emph{Post hoc} comparisons of error types showed that children chose the distractor set at a significantly higher rate in the Large-NR trials (21.83\%) compared to the Large-DR trials (5.75\%) (\(p < .001\)). In comparison, rates of incorrect responses due to choosing both sets and not choosing any set were statistically similar between the two trial types (\(p\)s \textgreater{} .05).

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:table2}Distribution of responses in Large-DR and Large-NR trials.}

\begin{tabular}{m{6cm}m{4.5cm}m{4.5cm}}
\toprule
 & \multicolumn{2}{c}{Number and Percentage of Trials per Trial Type} \\
\cmidrule(r){2-3}
Type of responses & Large trials with discriminable ratios & Large trials with an off-by-one difference\\
\midrule
Correct & 157 (69.47\%) & 123 (53.71\%)\\
Incorrect, chose both sets & 24 (10.62\%) & 25 (10.92\%)\\
Incorrect, did not choose a set & 32 (14.16\%) & 31 (13.54\%)\\
Incorrect, chose distractor set & 13 (5.75\%) & 50 (21.83\%)\\
\bottomrule
\end{tabular}

\end{threeparttable}
\end{center}

\end{table}

Similar to Experiment 1, we also conducted a follow-up analysis to explore how often participants gave the correct numerical response. On this measure, children succeeded in 80.35\% of small trials, 52.65\% of large trials with perceptually discriminable ratios, and 42.79\% of large trials with an off-by-one difference (Figure 4B). We also found variability in the CP knowers tested: Out of 80 children, 10 (12.50\%) succeeded in providing the correct numerical response for all trials, thus demonstrating some understanding that one-to-one correspondence between sets determines that those two sets share the same number label. Thirty-one children (38.75\%) succeeded in half or fewer trials. Out of 274 trials where participants gave the wrong numerical response, 65 trials (23.72\%) could be attributed to procedural error, where participants chose the correct set, but then counted wrongly. On 139 trials (50.73\%), participants counted the wrong set or both sets, which indicated failure in identifying the correct set for cardinal extension inference. Finally, on 70 trials (25.55\%), participants provided the wrong response but did not point to either set, which can either reflect overconfidence in estimating the number of items in the correct item set, or a lack of conceptual understanding about how the item set in one-to-one correspondence with the bunnies can be used to infer the number of bunnies. In comparison to the error pattern of CP knowers' numerical response in Experiment 1, Experiment 2 found a larger proportion of errors that came from counting the wrong set or both sets, with this type of mistake accounting for more than half or the errors.

To further investigate the effect of different trial types on children's numerical response, we constructed a set of GLMMs with the same fixed and random effect structure as the Correct Set Choice analysis. However, we removed the by-trial random intercept due to overfitting. Specifically, our base model had the formula Correct Numerical Response (0/1) \textasciitilde{} Age (z-scored) + (1 \textbar{} Participant), and we tested whether adding Trial Type (Small/Large-DR/Large-NR) improved the fit of the model. The model that best explained the data included both Age and Trial Type as predictors (compared against base model with only Age: \(\chi^2\)(2) = 118.96, \(p < .001\)). Older children were significantly better at providing the correct number of animals (\(\beta\) = 0.54, 95\% CI = {[}0.03, 1.05{]}, \(p = .036\)). Children's performance was also influenced by Trial Type (\(\chi^2\)(2) = 82.19, \(p < .001\)), and \emph{post hoc} pairwise comparisons with Bonferroni correction showed the same pattern of success across trial types as the above analysis. CP knowers were more successful in Small trials compared to Large-DR trials (\(z\) = 7.15, \(p < .001\)) and Large-NR trials (\(z\) = 8.97, \(p < .001\)), and success in Large-DR trials was also significantly more likely than in Large-NR trials (\(z\) = 2.84, \(p = .014\)).

As an exploratory analysis, we added children's Highest Count as a fixed effect to the best-performing models from the two analysis approaches above. Seventy-seven children (out of 80) provided a Highest Count, so we refitted our best-performing models to only the data from these children. We found the same pattern as in Experiment 1: Highest Count did not explain additional variability for either approach (Correct Set: \(\chi^2\)(1) = 1.92, \(p = .166\); Correct Numerical Response: \(\chi^2\)(1) = 1.94, \(p = .164\)).

During our analysis of data for Experiment 2, we became concerned that children might fail to select the correct set on large non-discriminable ratio (Large-NR) trials due to failures of memory. Specifically, given that the sets are not perceptually discriminable, after the bunnies disappeared into the school, children were required to recall which set was missing one item in order to prefer the other set that was an exact match. Therefore, children might fail at this task not because they lack an understanding of exact equality but because they can't recall which set was exactly equal to the number of bunnies. To explore this possibility, we tested an additional 23 CP knowers (13F, 10M; \(M_{age}\) = 4.83 {[}3.78; 5.87{]}; \(SD_{age}\) = 0.53) on a reduced version of the task that included just 3 Large-NR critical trials and asked them at the end of each trial which set had a missing element (``There was a bunny that was missing something. What was it missing, a {[}item 1{]} or {[}item 2{]}?''). We found that all 23 children remembered the missing item on all 3 trials. Critically, despite succeeding at this memory check, these children nevertheless showed the same rate of failure at cardinal extension, and chose the correct set only 49.28\% of the time. This provides strong evidence that even when children recognize that only one set exactly matches the target set, they often choose an approximate match anyway.

\hypertarget{discussion-1}{%
\subsection{Discussion}\label{discussion-1}}

Experiment 2 found that while children who were classified as CP knowers succeeded on trials with small subitizable sets and large, perceptually discriminable sets, they generally failed when the distractor set and target set could not be discriminated using approximate number representations, and differed by just 1 item. A follow-up study found that this was not merely due to difficulties recalling which set was an exact match, and that children who were able to identify which set was missing an item nevertheless often made an approximate match regardless. These results suggest that, even when 3- to 6-year-old CP knowers engage in cardinal extension, their dominant strategy is to extend number words to sets that are perceptually non-discriminable, even when one-to-one correspondence is violated. Additionally, we again found substantial variability in CP knowers' understanding of cardinal extension, with only a few children appearing to truly understand the relationship between one-to-one correspondence, equinumerosity, and cardinal extension.

\hypertarget{general-discussion}{%
\section{General Discussion}\label{general-discussion}}

In two experiments, we investigated the role that counting knowledge plays in children's understanding that equal sets should be given the same numerical label. We found three main results. First, compatible with some previous studies (e.g., Sarnecka \& Gelman, 2004; Sarnecka \& Wright, 2013), Experiment 1 found that CP knowers were more likely than subset knowers to infer that two sets should receive the same number label only if they are numerically equal. In fact, subset knowers performed at chance for both small and large sets. This provides evidence against the hypothesis (Sarnecka \& Gelman, 2004) that children understand that all number words have exact meanings even before children become CP knowers and can construct sets of large numbers. Second, Experiment 1 found that although many CP knowers are able to choose the correct item set to infer the quantity of a hidden set, many also failed, suggesting that simply learning to count does not guarantee understanding of cardinal extension. Together, these data suggest that although learning how counting can be used to construct sets plays some role in understanding cardinal extension, full knowledge of this principle may not emerge at the point that children become CP knowers. Third, Experiment 2 provided further evidence that CP knowledge does not alone furnish understanding of cardinal extension. Although CP knowers often correctly extended labels to equal sets when they were within the subitizable range or had perceptually discriminable ratios, they did not use violations of one-to-one correspondence as a cue to exact equality and often extended the same label to large sets that differed by 1 item. This suggests that CP knowers initially may extend number words to sets that are perceptually indiscriminable, without regard to whether they stand in one-to-one correspondence.

These results of these experiments are compatible with the hypothesis that full understanding of cardinal extension - and thus how number words label unique, exact, numerosities - does not emerge until sometime after children become competent counters. These data are difficult to explain for theories that predict earlier learning and particularly with the hypothesis that subset knowers understand that each number word denotes a unique, exact, cardinal number. When subset knowers - and some CP knowers - were asked to say how many animals were hidden in the school, they often counted the items of the wrong animal (Experiment 1). In doing so, these children failed to understand that only items from the same animal type - that were equal to the number of hidden animals - could predict the number of animals that were in the school.

Our results also call into question the hypothesis that becoming a CP knower supplies this knowledge. According to some previous reports, becoming a CP knower involves constructing an analogical mapping between the order of the count list and the set of ordered cardinalities created by increments of one individual, and therefore noticing that there is a one-to-one correspondence between number words and exact cardinal values, \emph{inter alia} (Carey, 2004, 2009). This supports the inference that only sets in one-to-one correspondence are equinumerous and can be denoted by the same number word (Le Corre \& Carey, 2007). This account posits that learning the cardinal principle entails understanding that numbers have exact meanings, and that number words can only be extended between sets in one-to-one correspondence. Against this, Experiment 1 found that many CP knowers still did not succeed at cardinal extension. Moreover, Experiment 2 found that CP knowers performed at chance when tested with perceptually non-discriminable sets that clearly violated one-to-one correspondence. Taken together, our results suggest that even when CP knowers seem to succeed in cardinal extension (as in Experiment 1), they extend number words based on their approximate match in magnitude, rather than on an exact match in number. Overall, this suggests that understanding of how number words encode exact equality continues to develop well after children master the counting procedures required to become a CP knower.

While our results are broadly consistent with some previous findings, we also introduce several new findings to the literature, which may at first appear to conflict with some past studies. For example, our finding that CP knowers extend cardinal labels to two sets even if they violate one-to-one correspondence seems, at first, to be at odds with previous studies that document an ability among CP knowers to judge that sets that differ by just 1 item should be labeled by different number words (Sarnecka \& Gelman, 2004; Sarnecka \& Wright, 2013). However, like our study, these studies also found variability in CP knowers' performance, suggesting that many CP knowers fail to recognize that equinumerous sets should receive the same label - the first component of cardinal extension. Also, it's unclear from past studies whether these children who extended the same label to two sets were sensitive to exact equality - the second component of cardinal extension. For example, in Sarnecka and Wright (2013) children had to judge whether two sets (5 vs.~6) were the same or different before being asked to provide numerical labels, and often received feedback when they failed to notice differences. Also, given how the items were arranged, children could use perceptual proxies like line length to approximate differences between the two sets, rather than using exact number. Similarly, as noted in the Introduction, although children in Sarnecka and Gelman (2004) judged that two previously equal sets should receive distinct numerical labels after one set had an item added or subtracted, children only needed to know the principle that ``different numbers get different labels'', or even ``different referents get different labels'', in keeping with the principle of contrast (see Brooks et al., 2013).

The central puzzle that flows from our findings is why CP knowers are able to use a one-to-one counting procedure to reliably count objects and construct large sets, but fail to use violations of one-to-one correspondence to inform cardinal extension. One possibility, proposed by Davidson et al. (2012), is that CP knowers have acquired the ability to construct large sets as one of several rote counting procedures that they acquire in early childhood {[}e.g., the `how-to-count' principles described in Gelman and Gallistel (1978); including the one-to-one principle, the stable order principle, and the last-word principle, \emph{inter alia}{]}. On this hypothesis, CP knowers might know how to accurately count and construct large sets, but not understand the underlying conceptual principles that these rote behaviors reflect; that is, CP knowers' understanding of counting reflects that they understand what counting is doing, but not what it is accomplishing (Heck, 2000). For example, when asked to `give six fish,' these children might follow a procedure in this form: `Begin counting from one, for each number word partition one item to a separate set, stop counting at six, and give all counted objects.' This procedure results in an accurate set of six, but requires minimal conceptual understanding of the meaning of `six' -- for example, that `six' denotes the same cardinality across any set constructed following the procedure or that `six' denotes `exactly six.' Lacking this understanding, these children might not realize that, if two sets stand in one-to-one correspondence, then counting one set indicates the cardinality of the second one. On this view, the ``CP'' in CP knower may not stand for ``cardinal principle'' but instead for ``cardinal procedure'', since many CP knowers appear to lack an understanding of how counting represents cardinality, but know how to deploy a procedure that nevertheless returns accurate cardinal labels.

However, alternative explanations for CP knowers' failure with cardinal extension also exist. One possibility, described by Schneider et al. (2022), is that very young children know that two sets are equal only if they stand in one-to-one correspondence, but they lack a reliable procedure for verifying this property for large sets - a critical prerequisite for adult-like cardinal extension. As noted by Schneider et al. (2022), studies of ``parallel individuation'' find that infants track small sets of hidden objects by assigning each a mental index, such that there is a one-to-one correspondence between these mental symbols and the things they represent (e.g., Feigenson \& Carey, 2003). However, these symbols are represented in parallel and are therefore subject to a capacity limit, such that infants cannot track more than 3 objects at a time. What infants lack, therefore, is a sequential, memory-free, verification procedure for establishing one-to-one correspondence. Schneider et al. (2022) argued that counting provides just such a procedure and solves the ``partition'' problem (Gelman \& Gallistel, 1978), by partitioning a set, one object at a time, into counted vs.~uncounted objects. As each item is counted, it is tagged with a number word, such that both that word and the object it labels are removed from further consideration (e.g., by setting it aside) and a one-to-one correspondence is created between words and objects. Consequently, to arrive at an exact response, the child needs only to keep track of where they currently are in the count list, and the next object they plan to count, making the process sequential and memory-free. One possibility, then, is that when children learn this one-to-one verification procedure, they extend the ability to sequentially map labels-to-objects to the problem of mapping objects-to-objects in sequence, a skill required for matching large sets.

One of the hypotheses outlined above suggests that children might struggle with cardinal extension because they lack conceptual understanding of counting, while the second hypothesis suggests they may struggle due to a lack of procedural knowledge for deploying their understanding of exact equality. Naturally, it's possible - and perhaps even likely - that both are true. First, there is independent evidence that procedural knowledge of counting generally precedes conceptual understanding from early in development (Fuson et al., 1983; Fuson, 1988), and that this continues past the CP knower stage, as Davidson et al. (2012) document. Second, there is evidence that children struggle with non-verbal set matching tasks (Schneider et al., 2022), much in the way that innumerate groups like the Piraha and Mundurucu do (Gordon, 2004; Pica et al., 2004). Additionally, it's possible that children also differ from adults in other ways. For example, even once children become able to verify one-to-one correspondence and understand that equal sets should always receive the same label, they may simply prefer to use approximate strategies (see Izard et al., 2014), or may not think that the difference between an exact and an approximate solution is important. As decades of research on Piagetian conservation demonstrated, children with relatively advanced numerical knowledge often simply understand the requirements of a task differently than adults and ``fail'' for pragmatic, rather than semantic reasons (McGarrigle \& Donaldson, 1974; Mehler \& Bever, 1967; Rose \& Blank, 1974).

Regardless of why some CP knowers fail at cardinal extension, it seems likely experience with counting plays a role in overcoming these challenges. Previous research has found that children are more successful at comparing cardinalities or constructing sets of the same quantities when they can count sets, as opposed to placing items in one-to-one correspondence (Cowan \& Daniels, 1989; Michie, 1984; Russac, 1978; Saxe, 1977). This suggests a progression whereby children become increasingly accurate at counting to establish cardinalities, with the ability to integrate this with reasoning about how one-to-one correspondence can be used to determine logical set equality developing afterwards. Furthermore, previous research has shown that children's counting proficiency seems to continue to develop even after they become CP knowers. For example, children who are classified as CP knowers on the basis of their ability to accurately give sets of 5 and 6 often make errors when counting larger sets, such as 7, 8, or 9 (Krajcsi \& Fintor, 2023; Wagner \& Johnson, 2011). Additionally, Le Corre et al. (2006) found that CP knowers vary in their ability to recognize mistakes in counting procedures (for similar results with preschoolers, see also Briars \& Siegler, 1984; Gelman et al., 1986; Gelman \& Meck, 1983). Particularly relevant to the current discussion, Muldoon et al. (2003) found that children's ability to detect violations of counting procedures predicted their success in a cardinal extension task (though this might be explained by the presence of subset knowers, since Muldoon et al. (2003) did not assess knower levels in this study). Perhaps as children gain more counting experience, they become better at deploying the counting procedures and noticing violations in counting. This might result in them realizing that violations of one-to-one between count words and items results in different numerical labels. More exposure to counting might also lead children to notice that adding or removing an item from a set results in a different cardinality. Given these possibilities, future studies should ask whether variability in cardinal extension performance among CP knowers might be explained by differing abilities to deploy counting procedures, as well as metacognitive abilities about the counting principles.

\newpage

\hypertarget{acknowledgements}{%
\section{Acknowledgements}\label{acknowledgements}}

This research was funded by a National Science Foundation award (\#2000827) to DB. We thank the participants, their parents, preschool teachers and directors, and the Fleet Science Center in San Diego, and also thank Elizabeth Hernandez, Christine Kwon, Urvi Maheshwari, and Mincong Wu for assistance with data collection. We are grateful for the feedback from the members of the Language and Development Lab at UC San Diego.

\newpage

\hypertarget{references}{%
\section{References}\label{references}}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-R-papaja}{}}%
Aust, F., \& Barth, M. (2022). \emph{{papaja}: {Prepare} reproducible {APA} journal articles with {R Markdown}}. \url{https://github.com/crsh/papaja}

\leavevmode\vadjust pre{\hypertarget{ref-R-lme4}{}}%
Bates, D., Mächler, M., Bolker, B., \& Walker, S. (2015). Fitting linear mixed-effects models using {lme4}. \emph{Journal of Statistical Software}, \emph{67}(1), 1--48. \url{https://doi.org/10.18637/jss.v067.i01}

\leavevmode\vadjust pre{\hypertarget{ref-boolos1986}{}}%
Boolos, G. (1986). Saving {Frege} from contradiction. \emph{Proceedings of the Aristotelian Society}, \emph{87}, 137--151.

\leavevmode\vadjust pre{\hypertarget{ref-briars1984}{}}%
Briars, D., \& Siegler, R. S. (1984). A featural analysis of preschoolers' counting knowledge. \emph{Developmental Psychology}, \emph{20}(4), 607. \url{https://doi.org/10.1037/0012-1649.20.4.607}

\leavevmode\vadjust pre{\hypertarget{ref-brooks2013}{}}%
Brooks, N., Audet, J., \& Barner, D. (2013). Pragmatic inference, not semantic competence, guides 3-year-olds' interpretation of unknown number words. \emph{Developmental Psychology}, \emph{49}(6), 1066. \url{https://doi.org/10.1037/a0029384}

\leavevmode\vadjust pre{\hypertarget{ref-carey2004}{}}%
Carey, S. (2004). Bootstrapping \& the origin of concepts. \emph{Daedalus}, \emph{133}, 59--68. \url{https://doi.org/10.1162/001152604772746701}

\leavevmode\vadjust pre{\hypertarget{ref-carey2009}{}}%
Carey, S. (2009). Where {Our} {Number} {Concepts} {Come} {From}. \emph{The Journal of Philosophy}, \emph{106}(4), 220--254. \url{https://doi.org/10.5840/jphil2009106418}

\leavevmode\vadjust pre{\hypertarget{ref-condry2008}{}}%
Condry, K. F., \& Spelke, E. S. (2008). The development of language and abstract concepts: {The} case of natural number. \emph{Journal of Experimental Psychology: General}, \emph{137}(1), 22--38. \url{https://doi.org/10.1037/0096-3445.137.1.22}

\leavevmode\vadjust pre{\hypertarget{ref-cordes2001}{}}%
Cordes, S., Gelman, R., Gallistel, C. R., \& Whalen, J. (2001). Variability signatures distinguish verbal from nonverbal counting for both large and small numbers. \emph{Psychonomic Bulletin \& Review}, \emph{8}, 698--707. \url{https://doi.org/10.3758/BF03196206}

\leavevmode\vadjust pre{\hypertarget{ref-cowan1989}{}}%
Cowan, R., \& Daniels, H. (1989). Children's use of counting and guidelines in judging relative number. \emph{British Journal of Educational Psychology}, \emph{59}(2), 200--210. \url{https://doi.org/10.1111/j.2044-8279.1989.tb03091.x}

\leavevmode\vadjust pre{\hypertarget{ref-davidson2012}{}}%
Davidson, K., Eng, K., \& Barner, D. (2012). Does learning to count involve a semantic induction? \emph{Cognition}, \emph{123}(1), 162--173. \url{https://doi.org/10.1016/j.cognition.2011.12.013}

\leavevmode\vadjust pre{\hypertarget{ref-decock2008}{}}%
Decock, L. (2008). Neo-fregeanism naturalized: The role of one-to-one correspondence in numerical cognition. \emph{Behavioral and Brain Sciences}, \emph{31}(6), 648--649. \url{https://doi.org/10.1017/S0140525X08005645}

\leavevmode\vadjust pre{\hypertarget{ref-dehaene1997}{}}%
Dehaene, S. (1997). \emph{The number sense: How the mind creates mathematics}. Oxford University Press.

\leavevmode\vadjust pre{\hypertarget{ref-dehaene2009}{}}%
Dehaene, S. (2009). Origins of mathematical intuitions: The case of arithmetic. \emph{Annals of the New York Academy of Sciences}, \emph{1156}(1), 232--259. \url{https://doi.org/10.1111/j.1749-6632.2009.04469.x}

\leavevmode\vadjust pre{\hypertarget{ref-gpower}{}}%
Faul, F., Erdfelder, E., Buchner, A., \& Lang, A.-G. (2009). Statistical power analyses using {G* Power 3.1}: Tests for correlation and regression analyses. \emph{Behavior Research Methods}, \emph{41}(4), 1149--1160. \url{https://doi.org/10.3758/BRM.41.4.1149}

\leavevmode\vadjust pre{\hypertarget{ref-feigenson2003}{}}%
Feigenson, L., \& Carey, S. (2003). Tracking individuals via object-files: Evidence from infants' manual search. \emph{Developmental Science}, \emph{6}(5), 568--584. \url{https://doi.org/10.1111/1467-7687.00313}

\leavevmode\vadjust pre{\hypertarget{ref-feigenson2004}{}}%
Feigenson, L., Dehaene, S., \& Spelke, E. (2004). Core systems of number. \emph{Trends in Cognitive Sciences}, \emph{8}(7), 307--314. \url{https://doi.org/10.1016/j.tics.2004.05.002}

\leavevmode\vadjust pre{\hypertarget{ref-R-car}{}}%
Fox, J., \& Weisberg, S. (2019). \emph{An {R} companion to applied regression} (Third). Sage. \url{https://socialsciences.mcmaster.ca/jfox/Books/Companion/}

\leavevmode\vadjust pre{\hypertarget{ref-frege1880}{}}%
Frege, G. (1880). \emph{Booles rechnende logik und die begriffsschrift}.

\leavevmode\vadjust pre{\hypertarget{ref-frege1884}{}}%
Frege, G. (1884). \emph{Die grundlagen der arithmetik: Eine logisch mathematische untersuchung über den begriff der zahl}. W. Koebner.

\leavevmode\vadjust pre{\hypertarget{ref-frydman1988}{}}%
Frydman, O., \& Bryant, P. (1988). Sharing and the understanding of number equivalence by young children. \emph{Cognitive Development}, \emph{3}(4), 323--339. \url{https://doi.org/10.1016/0885-2014(88)90019-6}

\leavevmode\vadjust pre{\hypertarget{ref-fuson1988}{}}%
Fuson, K. C. (1988). \emph{Children's counting and concepts of number}. Springer Science \& Business Media.

\leavevmode\vadjust pre{\hypertarget{ref-fuson1983}{}}%
Fuson, K. C., Secada, W. G., \& Hall, J. W. (1983). Matching, counting, and conservation of numerical equivalence. \emph{Child Development}, 91--97. \url{https://doi.org/10.2307/1129865}

\leavevmode\vadjust pre{\hypertarget{ref-gelman1978}{}}%
Gelman, R., \& Gallistel, C. R. (1978). \emph{The child's understanding of number}. Harvard University Press.

\leavevmode\vadjust pre{\hypertarget{ref-gelman1983}{}}%
Gelman, R., \& Meck, E. (1983). Preschoolers' counting: Principles before skill. \emph{Cognition}, \emph{13}(3), 343--359. \url{https://doi.org/10.1016/0010-0277(83)90014-8}

\leavevmode\vadjust pre{\hypertarget{ref-gelman1986}{}}%
Gelman, R., Meck, E., \& Merkin, S. (1986). Young children's numerical competence. \emph{Cognitive Development}, \emph{1}(1), 1--29. \url{https://doi.org/10.1016/S0885-2014(86)80021-1}

\leavevmode\vadjust pre{\hypertarget{ref-gordon2004}{}}%
Gordon, P. (2004). Numerical cognition without words: Evidence from {Amazonia}. \emph{Science}, \emph{306}(5695), 496--499. \url{https://doi.org/10.1126/science.1094492}

\leavevmode\vadjust pre{\hypertarget{ref-halberda2008}{}}%
Halberda, J., \& Feigenson, L. (2008). Developmental change in the acuity of the "number sense": The approximate number system in 3-, 4-, 5-, and 6-year-olds and adults. \emph{Developmental Psychology}, \emph{44}(5), 1457. \url{https://doi.org/10.1037/a0012682}

\leavevmode\vadjust pre{\hypertarget{ref-heck2000}{}}%
Heck, R. G. (2000). Cardinality, counting, and equinumerosity. \emph{Notre Dame Journal of Formal Logic}, \emph{41}(3), 187--209. \url{https://doi.org/10.1305/ndjfl/1038336841}

\leavevmode\vadjust pre{\hypertarget{ref-huntleyfenner2000}{}}%
Huntley-Fenner, G., \& Cannon, E. (2000). Preschoolers' magnitude comparisons are mediated by a preverbal analog mechanism. \emph{Psychological Science}, \emph{11}(2), 147--152. \url{https://doi.org/10.1111/1467-9280.00230}

\leavevmode\vadjust pre{\hypertarget{ref-izard2014}{}}%
Izard, V., Streri, A., \& Spelke, E. S. (2014). Toward exact number: {Young} children use one-to-one correspondence to measure set identity but not numerical equality. \emph{Cognitive Psychology}, \emph{72}, 27--53. \url{https://doi.org/10.1016/j.cogpsych.2014.01.004}

\leavevmode\vadjust pre{\hypertarget{ref-krajcsi2023}{}}%
Krajcsi, A., \& Fintor, E. (2023). A refined description of initial symbolic number acquisition. \emph{Cognitive Development}, \emph{65}, 101288. \url{https://doi.org/10.1016/j.cogdev.2022.101288}

\leavevmode\vadjust pre{\hypertarget{ref-lecorre2007}{}}%
Le Corre, M., \& Carey, S. (2007). One, two, three, four, nothing more: An investigation of the conceptual sources of the verbal counting principles. \emph{Cognition}, \emph{105}(2), 395--438. \url{https://doi.org/10.1016/j.cognition.2006.10.005}

\leavevmode\vadjust pre{\hypertarget{ref-lecorre2006}{}}%
Le Corre, M., Van de Walle, G., Brannon, E. M., \& Carey, S. (2006). Re-visiting the competence/performance debate in the acquisition of the counting principles. \emph{Cognitive Psychology}, \emph{52}(2), 130--169. \url{https://doi.org/10.1016/j.cogpsych.2005.07.002}

\leavevmode\vadjust pre{\hypertarget{ref-R-emmeans}{}}%
Lenth, R. V. (2023). \emph{Emmeans: Estimated marginal means, aka least-squares means}. \url{https://CRAN.R-project.org/package=emmeans}

\leavevmode\vadjust pre{\hypertarget{ref-mcgarrigle1974}{}}%
McGarrigle, J., \& Donaldson, M. (1974). Conservation accidents. \emph{Cognition}, \emph{3}(4), 341--350. \url{https://doi.org/10.1016/0010-0277(74)90003-1}

\leavevmode\vadjust pre{\hypertarget{ref-mehler1967}{}}%
Mehler, J., \& Bever, T. G. (1967). Cognitive capacity of very young children. \emph{Science}, \emph{158}(3797), 141--142. \url{https://doi.org/10.1126/science.158.3797.141}

\leavevmode\vadjust pre{\hypertarget{ref-michie1984}{}}%
Michie, S. (1984). Number understanding in preschool children. \emph{British Journal of Educational Psychology}, \emph{54}(3), 245--253. \url{https://doi.org/10.1111/j.2044-8279.1984.tb02588.x}

\leavevmode\vadjust pre{\hypertarget{ref-muldoon2003}{}}%
Muldoon, K., Lewis, C., \& Freeman, N. H. (2003). Putting counting to work: Preschoolers' understanding of cardinal extension. \emph{International Journal of Educational Research}, \emph{39}(7), 695--718. \url{https://doi.org/10.1016/j.ijer.2004.10.006}

\leavevmode\vadjust pre{\hypertarget{ref-muldoon2005}{}}%
Muldoon, K., Lewis, C., \& Towse, J. (2005). Because it's there! Why some children count, rather than infer numerical relationships. \emph{Cognitive Development}, \emph{20}(3), 472--491. \url{https://doi.org/10.1016/j.cogdev.2005.05.008}

\leavevmode\vadjust pre{\hypertarget{ref-piaget1965}{}}%
Piaget, J. (1965). The stages of the intellectual development of the child. \emph{Educational Psychology in Context: Readings for Future Teachers}, \emph{63}(4), 98--106.

\leavevmode\vadjust pre{\hypertarget{ref-pica2004}{}}%
Pica, P., Lemer, C., Izard, V., \& Dehaene, S. (2004). Exact and approximate arithmetic in an {Amazonian} indigene group. \emph{Science}, \emph{306}(5695), 499--503. \url{https://doi.org/10.1126/science.1102085}

\leavevmode\vadjust pre{\hypertarget{ref-R-base}{}}%
R Core Team. (2022). \emph{R: A language and environment for statistical computing}. R Foundation for Statistical Computing. \url{https://www.R-project.org/}

\leavevmode\vadjust pre{\hypertarget{ref-rose1974}{}}%
Rose, S. A., \& Blank, M. (1974). The potency of context in children's cognition: An illustration through conservation. \emph{Child Development}, 499--502. \url{https://doi.org/10.2307/1127977}

\leavevmode\vadjust pre{\hypertarget{ref-russac1978}{}}%
Russac, R. (1978). The relation between two strategies of cardinal number: Correspondence and counting. \emph{Child Development}, 728--735. \url{https://doi.org/10.2307/1128241}

\leavevmode\vadjust pre{\hypertarget{ref-sarnecka2004}{}}%
Sarnecka, B., \& Gelman, S. A. (2004). Six does not just mean a lot: Preschoolers see number words as specific. \emph{Cognition}, \emph{92}(3), 329--352. \url{https://doi.org/10.1016/j.cognition.2003.10.001}

\leavevmode\vadjust pre{\hypertarget{ref-sarnecka2013}{}}%
Sarnecka, B., \& Wright, C. E. (2013). The {Idea} of an {Exact} {Number}: {Children}'s {Understanding} of {Cardinality} and {Equinumerosity}. \emph{Cognitive Science}, \emph{37}(8), 1493--1506. \url{https://doi.org/10.1111/cogs.12043}

\leavevmode\vadjust pre{\hypertarget{ref-saxe1977}{}}%
Saxe, G. B. (1977). A developmental analysis of notational counting. \emph{Child Development}, 1512--1520. \url{https://doi.org/10.2307/1128514}

\leavevmode\vadjust pre{\hypertarget{ref-schneider2022}{}}%
Schneider, R. M., Brockbank, E., Feiman, R., \& Barner, D. (2022). Counting and the ontogenetic origins of exact equality. \emph{Cognition}, \emph{218}, 104952. \url{https://doi.org/10.1016/j.cognition.2021.104952}

\leavevmode\vadjust pre{\hypertarget{ref-slusser2011}{}}%
Slusser, E. B., \& Sarnecka, B. W. (2011). Find the picture of eight turtles: A link between children's counting and their knowledge of number word semantics. \emph{Journal of Experimental Child Psychology}, \emph{110}(1), 38--51. \url{https://doi.org/10.1016/j.jecp.2011.03.006}

\leavevmode\vadjust pre{\hypertarget{ref-sophian1995}{}}%
Sophian, C., Wood, A. M., \& Vong, K. I. (1995). Making numbers count: The early development of numerical inferences. \emph{Developmental Psychology}, \emph{31}(2), 263. \url{https://doi.org/10.1037/0012-1649.31.2.263}

\leavevmode\vadjust pre{\hypertarget{ref-wagner2011}{}}%
Wagner, J. B., \& Johnson, S. C. (2011). An association between understanding cardinality and analog magnitude representations in preschoolers. \emph{Cognition}, \emph{119}(1), 10--22. \url{https://doi.org/10.1016/j.cognition.2010.11.014}

\leavevmode\vadjust pre{\hypertarget{ref-whalen1999}{}}%
Whalen, J., Gallistel, C. R., \& Gelman, R. (1999). Nonverbal counting in humans: The psychophysics of number representation. \emph{Psychological Science}, \emph{10}(2), 130--137. \url{https://doi.org/10.1111/1467-9280.00120}

\leavevmode\vadjust pre{\hypertarget{ref-R-ggplot2}{}}%
Wickham, H. (2016). \emph{ggplot2: Elegant graphics for data analysis}. Springer-Verlag New York. \url{https://ggplot2.tidyverse.org}

\leavevmode\vadjust pre{\hypertarget{ref-R-tidyverse}{}}%
Wickham, H., Averick, M., Bryan, J., Chang, W., McGowan, L. D., François, R., Grolemund, G., Hayes, A., Henry, L., Hester, J., Kuhn, M., Pedersen, T. L., Miller, E., Bache, S. M., Müller, K., Ooms, J., Robinson, D., Seidel, D. P., Spinu, V., \ldots{} Yutani, H. (2019). Welcome to the {tidyverse}. \emph{Journal of Open Source Software}, \emph{4}(43), 1686. \url{https://doi.org/10.21105/joss.01686}

\leavevmode\vadjust pre{\hypertarget{ref-R-cowplot}{}}%
Wilke, C. O. (2024). \emph{Cowplot: Streamlined plot theme and plot annotations for 'ggplot2'}. \url{https://CRAN.R-project.org/package=cowplot}

\leavevmode\vadjust pre{\hypertarget{ref-wynn1990}{}}%
Wynn, K. (1990). Children's understanding of counting. \emph{Cognition}, \emph{36}(2), 155--193. \url{https://doi.org/10.1016/0010-0277(90)90003-3}

\leavevmode\vadjust pre{\hypertarget{ref-wynn1992}{}}%
Wynn, K. (1992). Children's acquisition of the number words and the counting system. \emph{Cognitive Psychology}, \emph{24}(2), 220--251. \url{https://doi.org/10.1016/0010-0285(92)90008-P}

\end{CSLReferences}


\end{document}
